In [1]:
import torch
import numpy as np

## 1. Getting Started

In [2]:
# create a 1-D tensor with 32-bit floating-point numbers
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
# NUMber of ELements in tensor
x.numel()

12

In [4]:
# shape of tensor
x.shape

torch.Size([12])

In [5]:
# Reshape the tensor to 3 rows and 4 columns
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
# Create a 2-D tensor with 2 rows and 3 columns filled with zeros
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# with 1s
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# Create a 2-D tensor with 3 rows and 4 columns filled with random numbers 
# from a standard normal distribution
torch.randn(3, 4)

tensor([[-1.3304,  0.8724, -0.2965, -0.5661],
        [ 0.9277,  0.4877,  1.0756,  0.0644],
        [-1.6332, -0.4638, -0.0698,  0.3241]])

## 2. Indexing and Slicing

In [9]:
# last row and slice of 2nd and 3rd columns
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [10]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
# set first two rows to 12
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 3. Operations

In [12]:
# Compute the exponential of each element in the tensor
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [13]:
# Element-wise operations
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x- y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# concate two tensors along rows (dim=0) and columns (dim=1)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# Compare two tensors element-wise
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
X.sum()

tensor(66.)

In [17]:
# Create a tensor of shape (3, 1) -> This is a COLUMN vector
# Values: [[0], [1], [2]]
a = torch.arange(3).reshape((3, 1))

# Create a tensor of shape (1, 2) -> This is a ROW vector
# Values: [[0, 1]]
b = torch.arange(2).reshape((1, 2))

# --- The Broadcasting Operation ---
# Since shapes (3,1) and (1,2) are different but compatible, 
# PyTorch expands them both to shape (3,2) automatically.
# 'a' is copied across columns, 'b' is copied across rows.
result = a + b 

# Final Shape: (3, 2)
# Final Values:
# [[0+0, 0+1],  -> [[0, 1],
#  [1+0, 1+1],  ->  [1, 2],
#  [2+0, 2+1]]  ->  [2, 3]]
result


tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 4. Saving Memory

In [18]:
# Y get a new memory address after the operation
before = id(Y)
Y = Y + X
print(id(Y) == before)
print(id(Y))

False
126587397203712


In [19]:
# In-place operation: Y keeps the same memory address
Z = torch.zeros_like(Y) # create a tensor of the same shape with 0.
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 126587397712816
id(Z): 126587397712816


In [20]:
# In-place operation: X keeps the same memory address if use +=
before = id(X)
X += Y
id(X) == before

True

# 5. Conversion to Other Python Objects

In [21]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

## 6. Exercises
- 1. Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.
- 2. Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [22]:
# 1: 2D tensor comparison
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(X < Y)
print(X > Y)

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [23]:
# 2: Broadcasting example
# A is (3, 1, 4)
A = torch.arange(12).reshape((3, 1, 4))

# B is (1, 2, 1)
B = torch.arange(2).reshape((1, 2, 1))

C = A + B
print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")
print(f"Shape of C: {C.shape}")
print(C)

Shape of A: torch.Size([3, 1, 4])
Shape of B: torch.Size([1, 2, 1])
Shape of C: torch.Size([3, 2, 4])
tensor([[[ 0,  1,  2,  3],
         [ 1,  2,  3,  4]],

        [[ 4,  5,  6,  7],
         [ 5,  6,  7,  8]],

        [[ 8,  9, 10, 11],
         [ 9, 10, 11, 12]]])
