In [2]:
import torch

In [4]:
# Basic arithmetic operations with Scalar Tensors
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
# tensor vector
x = torch.arange(4)
x, x[2], len(x), x.shape

(tensor([0, 1, 2, 3]), tensor(2), 4, torch.Size([4]))

In [5]:
# Tensor matrix
A = torch.arange(6).reshape(3, 2)
A, A.T, A.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]),
 torch.Size([3, 2]))

In [8]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A, A == A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [6]:
# Tensor
torch.arange(24, dtype=torch.int32).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [ ]:
#5 Basic Properties of Tensor Arithmmetic

In [7]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() # Assign a copy of A to B by allocating new memory
A, A + B, A * B, A / B, A**B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[nan, 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.0000e+00, 1.0000e+00, 4.0000e+00],
         [2.7000e+01, 2.5600e+02, 3.1250e+03]]))

In [12]:
# The result of A * B is the element-wise product of
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [9]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [11]:
# 6 Reduction Operations
x = torch.arange(3, dtype=torch.float32)
x, x.sum() # sum
x.shape

torch.Size([3])

In [12]:
# Tensor operations by col or rows
A.shape, A.sum(axis=0), A.sum(axis=1)

(torch.Size([2, 3]), tensor([3., 5., 7.]), tensor([ 3., 12.]))

In [13]:
A.sum(axis=[0, 1]) == A.sum() # Same as A.sum()

tensor(True)

In [20]:
# mean
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [14]:
# dot product
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [15]:
torch.sum(x * y)

tensor(3.)

In [24]:
# Matrix-Vector Multiplication
A, x, A.shape, x.shape, torch.mv(A, x), A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 torch.Size([2, 3]),
 torch.Size([3]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

In [25]:
# matrix-matrix multiplication
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [ ]:
u= torch.tensor([3.0, -4.0])
torch.norm(u) # L2 norm by default

tensor(5.)

In [ ]:
torch.abs(u).sum() # L1 norm

tensor(7.)

In [ ]:
torch.norm(torch.ones((4, 9))) # the norm of a matrix

tensor(6.)