In [9]:
import torch

In [10]:
# 1 a simple function
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [11]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None by default

In [18]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
# Compute gradients
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
# reset gradients
x.grad.zero_() # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### Backward for Non-Scalar Variables

In [ ]:
# 1. Clear previous gradients. 
# PyTorch accumulates gradients by default; if we don't zero them out, 
# the new results will be added to whatever was stored in x.grad previously.
if x.grad is not None:
    x.grad.zero_()

# 2. Define the Forward Pass.
# We are creating the function y = f(x) = x^2.
y = x * x

# 3. Perform the Backward Pass (Backpropagation).
# Since 'y' is a vector (tensor) and not a single scalar (like a loss value), 
# we must provide a 'gradient' argument of the same shape. 
# Passing torch.ones() essentially means dL/dy = 1 for each element.
# Mathematically, this computes dy/dx = 2*x.
y.backward(gradient=torch.ones(len(y))) 

# Note: The commented alternative 'y.sum().backward()' is more common. 
# It turns the vector into a scalar first, which simplifies the math 
# to the same result.

# 4. Access the result.
# x.grad now holds the values of the derivative evaluated at the points in x.
x.grad

tensor([0., 2., 4., 6.])